# Generated by Django 4.0.6 on 2022-08-01 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rename_neighborhoods_neighborhood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='borough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurants.borough'),
        ),
    ]
