# Generated by Django 4.2.6 on 2023-10-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_borough_alter_neighborhood_borough'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
